import type { Metadata } from "next";
import localFont from 'next/font/local'
import './globals.css'
import { Toaster } from 'react-hot-toast'


const satoshiFont = localFont({
  src: [
    {
      path: '../public/font/Satoshi-Medium.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/font/Satoshi-Medium.otf',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-satoshi',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={satoshiFont.className}>
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
          {children}
      </body>
    </html>
  );
}
